archlinux system update script

diff --git a/Scripts/bin/sysupdate b/Scripts/bin/sysupdate
--- a/Scripts/bin/sysupdate
+++ b/Scripts/bin/sysupdate
@@ -1,47 +1,41 @@
 #! /bin/bash
 
-#THIS SCRIPT IS INCOMPLETE AND BUGGY AS HELL
-echo "NOT WORKING YET"
-exit 3
-
 #This script peforms automated system update, it also checks if there is a kernel update and if so,
 #it reinstalls the broadcom driver
 
 WAR="WARNING! This script will perform an automated system update, are you sure you want to proceed?(y/n) "
-LIN="Kernel update avaible. Will reinstall Broadcom driver."
+LIN="Kernel update available. Broadcom driver will be reinstalled. Updating..."
 REB="Update complete. Reboot?(y/n) "
-
 
 read -p "$WAR"  choicewar
 case "$choicewar" in
 	y|Y ) echo "Continuing...";;
-	n|N	) echo "Aborting update!" && exit 1;;
-	*	) echo "Invalid argument" && exit 1;;
+	n|N	) echo "Aborting." && exit 1;;
+	*	) echo "Invalid argument." && exit 2;;
 esac
 
 echo
 
 #update package list
-pacman -Syy
+pacman -Sy
 
 #pacman -Qu will list packages to be updated
 #this aint right -- Trying new fix (adding $(command) to nest variable)
 KER=$(pacman -Qu | grep linux)
 if [ -z "$KER" ] #if no kernel packages, update normally
 then
-	echo "Standard update..."
-	yaourt -Syu
+	echo "No kernel updates available. Updating..."
+	pacman -Syu
 else			#else reinstall broadcom driver
 	echo "$LIN"
-	yaourt -Syu
+	pacman -Syu
 	yaourt -S broadcom-wl --noconfirm
 fi
 
-echo
-
+echo ''
 #reboot(y)
 read -p "$REB" choice
 case "$choice" in
-	y|Y ) reboot;;
+	y|Y ) echo "Rebooting..." && reboot;;
 	* )	echo "Exiting sysupdate.";;
 esac
